name: mobile
description: "new flash screen "

publish_to: 'none'

version: 2.2.2+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  video_player: ^2.9.5
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icon/psars2_foreground.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/psars2_foreground.png"

  remove_alpha_ios: true



# Your existing pubspec content...


# Paste it at the very bottom, completely aligned to the left edge
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  image: "assets/icon/psars2_splash.png"
  image_dark: "assets/icon/psars2_splash.png"

  android_12:
    color: "#ffffff"
    color_dark: "#121212"
    image: "assets/icon/psars2_splash.png"

  fullscreen: true
